os: osx
osx_image: xcode14.2
language: swift
script: xcodebuild clean build test -workspace QuizApp/QuizApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=Any iOS Simulator Device" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO