name: iOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Build and Test
      run: |
        xcodebuild clean build test -workspace QuizApp/QuizApp.xcworkspace \
        -scheme "CI" -sdk iphonesimulator \
        -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" \
        ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO