name: iOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -s '/Applications/Xcode_14.2.app/Contents/Developer'

    - name: Build and Test
      run: |
        xcodebuild clean build test -workspace QuizApp/QuizApp.xcworkspace \
        -scheme "CI" -sdk iphonesimulator \
        -destination "platform=iOS Simulator,id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder" \
        ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO